version: '3.1'
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    container_name: jdrai-mongodb
    environment:
      - MONGO_INITDB_DATABASE=jdrai
      - MONGO_INITDB_ROOT_USERNAME=jdrai
      - MONGO_INITDB_ROOT_PASSWORD=jdrai
